In [1]:
%load_ext autoreload
%autoreload 2

# Import Libraries

In [2]:
import pandas as pd

from mra_midas_skin_cancer_ml.utils.merge_image_pred import merge_image_pred

# Merge Test Results

In [8]:
# Merge image prediction results
image_pred_dfs = merge_image_pred()

for split, df in image_pred_dfs.items():
    print(f"Displaying {split} split:")
    display(df.head(3))

Length of 1ft-train key rows: 830
Length of 1ft-train pred rows: 830
Length of 1ft-train merged rows: 830
Length of 1ft-val key rows: 100
Length of 1ft-val pred rows: 100
Length of 1ft-val merged rows: 100
Length of 1ft-test key rows: 91
Length of 1ft-test pred rows: 91
Length of 1ft-test merged rows: 91
Length of 1ft combined rows: 1021
Length of 6in-train key rows: 833
Length of 6in-train pred rows: 833
Length of 6in-train merged rows: 833
Length of 6in-val key rows: 101
Length of 6in-val pred rows: 101
Length of 6in-val merged rows: 101
Length of 6in-test key rows: 94
Length of 6in-test pred rows: 94
Length of 6in-test merged rows: 94
Length of 6in combined rows: 1028
Length of dscope-train key rows: 834
Length of dscope-train pred rows: 834
Length of dscope-train merged rows: 834
Length of dscope-val key rows: 101
Length of dscope-val pred rows: 101
Length of dscope-val merged rows: 101
Length of dscope-test key rows: 93
Length of dscope-test pred rows: 93
Length of dscope-test merged rows: 93
Length of dscope combined rows: 1028
Displaying 1ft split:

,lesion_key,midas_record_id,midas_file_name,matched_file,midas_path_binary,split,1ft_malignant_probability,1ft_prediction_label
0,1_chest_8.0x5.0,1,s-prd-398966407.jpg,s-prd-398966407.jpg,malignant,train,0.550893,malignant
1,1_l lower back_6.0x5.0,1,s-prd-398967381.jpg,s-prd-398967381.jpg,benign,train,0.606678,malignant
2,1_left upper buttock_5.0x3.0,1,s-prd-398968016.jpg,s-prd-398968016.jpg,benign,train,0.480606,malignant

Displaying 6in split:

,lesion_key,midas_record_id,midas_file_name,matched_file,midas_path_binary,split,6in_malignant_probability,6in_prediction_label
0,1_chest_8.0x5.0,1,s-prd-398966642.jpg,s-prd-398966642.jpg,malignant,train,0.583346,malignant
1,1_left upper buttock_5.0x3.0,1,s-prd-398968141.jpg,s-prd-398968141.jpg,benign,train,0.361439,benign
2,2_right upper eyelid_4.0x2.0,2,s-prd-399001840.jpg,s-prd-399001840_cropped.jpg,benign,train,0.387896,benign

Displaying dscope split:

,lesion_key,midas_record_id,midas_file_name,matched_file,midas_path_binary,split,dscope_malignant_probability,dscope_prediction_label
0,1_chest_8.0x5.0,1,s-prd-398966845.jpg,s-prd-398966845.jpg,malignant,train,0.966925,malignant
1,1_l lower back_6.0x5.0,1,s-prd-398967587.jpg,s-prd-398967587.jpg,benign,train,0.273244,benign
2,2_right upper eyelid_4.0x2.0,2,s-prd-399002046.jpg,s-prd-399002046.jpg,benign,train,0.514993,malignant